// Shared itinerary content for all three designs.
// Finalized bilingual (EN + 中文) itinerary data; addresses & Amap links verbatim.

let _id = 0;
const uid = () => 'x' + (++_id);

const day = (date, dayLabel, titleEn, titleZh, items) => ({ date, dayLabel, title: { en: titleEn, zh: titleZh }, items });

// ---- real-data factories (used by all cities) ----
// stop factory with a real address + Amap URL
const itemB = (time, type, en, zh, hoodEn, hoodZh, addr, url, booking, descEn, descZh, nearby) => ({
  id: uid(),
  time,
  type,
  name: { en, zh },
  neighborhood: { en: hoodEn, zh: hoodZh },
  address: { text: addr, mapUrl: url },
  bookingRequired: !!booking,
  desc: { en: descEn, zh: descZh },
  nearby: nearby || [],
});
// nearby factory with a real address + Amap URL
const nearB = (type, en, zh, note_en, note_zh, addr, url) => ({
  type,
  name: { en, zh },
  distance: '',
  address: { text: addr, mapUrl: url },
  note: { en: note_en, zh: note_zh },
});

// ============================ GUANGZHOU ============================
// Real finalized itinerary. Addresses & Amap links verbatim.

const GZ_HOTEL_ADDR = '广州市越秀区北京路238号恒润广场1楼停车场入口旁';
const GZ_HOTEL_MAP = 'https://www.amap.com/place/B0GRHKO2I9';
const GZ_AIRPORT_ADDR = '广州白云国际机场';
const GZ_AIRPORT_MAP = 'https://www.amap.com/place/B00140NZIQ';

const guangzhou = {
  id: 'gz',
  name: { en: 'Guangzhou', zh: '广州' },
  dateRange: 'Jul 26 – 29',
  hotel: {
    name: { en: 'Guangzhou Hakka Apartment Beijing Road', zh: '金铂·茶阳复式公寓（北京路店）' },
    address: { text: GZ_HOTEL_ADDR, mapUrl: GZ_HOTEL_MAP },
    phone: '+86 20 8054 4120', confirmation: '1013153654',
    checkIn: { time: '14:00', note: { en: 'Lead guest changed to Michelle Xin Yi Liang; otherwise show the confirmation PDF.', zh: '主入住人已改为Michelle Xin Yi Liang；如有问题请出示确认单PDF。' } },
    checkOut: { time: '12:00', note: { en: 'Ask the host about keeping our bags until we leave.', zh: '与房东确认能否寄存行李至我们离开。' } },
    wifi: { en: 'Premium Wi-Fi included, no password', zh: '包含高级 Wi-Fi，无需密码' },
    notes: [
      { en: 'Entrance is beside the Hengrun Plaza L1 parking entrance', zh: '入口在恒润广场1楼停车场入口旁' },
    ],
  },
  mustEats: [
    { name: { en: 'Morning Dim Sum', zh: '早茶点心' }, note: { en: 'Shrimp dumplings & buns', zh: '虾饺与包点' } },
    { name: { en: 'Wonton Noodles', zh: '云吞面' }, note: { en: 'Springy egg noodles', zh: '弹牙鸡蛋面' } },
    { name: { en: 'Roast Goose', zh: '烧鹅' }, note: { en: 'Crispy skin classic', zh: '脆皮经典' } },
    { name: { en: 'Rice Noodle Rolls', zh: '肠粉' }, note: { en: 'Silky steamed rolls', zh: '滑嫩蒸卷' } },
    { name: { en: 'Double-skin Milk', zh: '双皮奶' }, note: { en: 'Warm milk custard', zh: '温热奶羹' } },
    { name: { en: 'Char Siu', zh: '叉烧' }, note: { en: 'Honey-glazed pork', zh: '蜜汁叉烧' } },
    { name: { en: 'Claypot Rice', zh: '煲仔饭' }, note: { en: 'Sizzling rice with cured meats', zh: '腊味煲仔饭，锅巴香脆' } },
  ],
  days: [
    day('Jul 26', 'Sun', 'Arrival, Lingnan History & Pearl River Night Cruise', '抵达·岭南历史·珠江夜游', [
      itemB('08:55', 'transit', 'Arrival — Guangzhou Baiyun International Airport', '抵达·广州白云国际机场', 'Baiyun', '白云区',
        GZ_AIRPORT_ADDR, GZ_AIRPORT_MAP, false,
        'Steven arrives at Guangzhou Airport; will go to the hotel to drop off bags and meet up for dim sum.',
        'Steven抵达广州白云机场；先到民宿放下行李，再与大家会合去饮茶。'),
      itemB('12:00', 'meal', 'Dian Dou De (Beijing Road No. 2 Branch)', '点都德（北京路贰店）', 'Beijing Road', '北京路',
        '广州市越秀区北京路352、354号', 'https://www.amap.com/place/B0FFK6QJP6', false,
        'Advance booking is not required, but a reservation or remote queue number is advisable for seven. Check Dian Dou De’s current WeChat channel or 美味不用等.',
        '无需提前订位，但七人建议预约或线上取号。查看点都德官方微信或"美味不用等"。', [
        nearB('shopping', 'Beijing Road Pedestrian Street', '北京路步行街',
          'Very touristy, pedestrian-street browsing.',
          '很热闹的旅游步行街，随意逛逛。',
          '广州市越秀区北京路（公园前站E口步行约170米）', 'https://www.amap.com/place/B00141RH20'),
        nearB('restaurant', 'Ren Xin Lao Pu Flagship', '仁信老铺旗舰店',
          'Classic Cantonese dairy dessert known for their double-skin milk.',
          '经典粤式奶制甜品老铺，以双皮奶闻名。',
          '广州市越秀区北京路327号1-2层', 'https://www.amap.com/place/B0FFFPAIUH'),
        nearB('sight', 'Beijing Road Millennium Ancient Road Ruins', '北京路千年古道遗址',
          'Street-level archaeology: stacked road surfaces from several dynasties directly beneath modern Beijing Road.',
          '街面考古：现代北京路正下方叠压着多个朝代的路面遗迹。',
          '广州市越秀区北京路文化旅游区', 'https://www.amap.com/place/B00140T1AY'),
      ]),
      itemB('13:30', 'sight', 'Sacred Heart Cathedral', '石室圣心大教堂', 'Yuexiu', '越秀区',
        '广州市越秀区一德路旧部前56号', 'https://www.amap.com/place/B00140UHIZ', false,
        'Public visitation hours run until 14:30 on Sundays; otherwise check out the exterior and take photos. Defining Guangzhou Gothic landmark.',
        '周日对外开放参观至14:30；错过也可在外面拍照打卡。广州标志性的哥特式建筑。', [
        nearB('restaurant', 'MOTTLE Cafe (Sacred Heart Branch)', 'MOTTLE Cafe（石室店）',
          'Trendy on Rednote; directly beside the cathedral square for specialty coffee and dessert.',
          '小红书上很火；就在教堂广场旁，精品咖啡与甜品。',
          '广州市越秀区劳动路17号(一德路地铁站B口步行320米)', 'https://www.amap.com/place/B0FFK68Z7B'),
      ]),
      itemB('15:00', 'sight', 'Nanyue King Museum — Palace Exhibition', '南越王博物院（王宫展区）', 'Beijing Road', '北京路',
        '广州市越秀区中山四路316号', 'https://www.amap.com/place/B00140USZS', true,
        'Summer last entry is 17:00 and it closes at 18:00 — if we miss this, it’s alright. Book in WeChat 南越王博物院 via 王宫展区 → 门票讲解预约. Official visit guide: https://www.nywmuseum.org.cn/News/VisitIndex/Visit',
        '夏季17:00停止入场，18:00闭馆——错过也没关系。在微信"南越王博物院"经"王宫展区→门票讲解预约"购票。官方参观指南：https://www.nywmuseum.org.cn/News/VisitIndex/Visit'),
      itemB('17:30', 'meal', 'Flexible Dinner', '灵活晚餐', 'Haizhu', '海珠区',
        '广州市海珠区', 'https://www.amap.com/place/BZ7QP702CE', false,
        'Preferably somewhere closer to the Binjiang West Pearl River because we’ll go on the evening cruise afterwards; walk the Binjiang West promenade until it’s time, for minimal stress and planning.',
        '尽量选在滨江西珠江边附近——晚饭后就去乘夜游船。吃完沿滨江西步道散步等开船，轻松不赶。'),
      itemB('21:10', 'activity', 'Pearl River Night Cruise from Tianzi Wharf', '珠江夜游·天字码头', 'Yuexiu', '越秀区',
        '广州市越秀区沿江中路天字码头', 'https://www.amap.com/place/B0FFG22YZJ', true,
        'Arrive 15–20 minutes before departure. Must book ahead, but departures run every 20–30 minutes; approximate cruise time 1 hour. Make sure to book the upper floor with exterior access for the best views and photographs. Official booking: https://ykz.zjyeyou.com/',
        '开船前15–20分钟到达。需提前订票，班次约每20–30分钟一班；航程约1小时。务必订带露天区域的上层船票，视野和拍照最佳。官方购票：https://ykz.zjyeyou.com/', [
        nearB('restaurant', 'Wentong Ice Room (Huifu East Road)', '文通冰室（惠福东路店）',
          'About 10 minutes toward Huifu East Road for milk tea and Hong Kong-style snacks.',
          '往惠福东路方向约10分钟；奶茶与港式小食。',
          '广州市越秀区惠福东路522(距地铁6号线北京路B出口步行660m)', 'https://www.amap.com/place/B0G069PTGD'),
        nearB('restaurant', 'Ren Xin Lao Pu Flagship', '仁信老铺旗舰店',
          'Towards hotel direction; double-skin milk.',
          '在回民宿的方向；双皮奶。',
          '广州市越秀区北京路327号1-2层', 'https://www.amap.com/place/B0FFFPAIUH'),
      ]),
    ]),
    day('Jul 27', 'Mon', 'Old Xiguan by Day & Night', '老西关·日与夜', [
      itemB('09:00', 'meal', 'Panxi Restaurant', '泮溪酒家', 'Liwan', '荔湾区',
        '广州市荔湾区龙津西路151号', 'https://www.amap.com/place/B00140GQNN', true,
        'Michelin-recommended dim sum. Try to request a table for seven near the garden.',
        '米其林推荐早茶。尽量订一张靠园林景观的七人桌。'),
      itemB('10:45–12:00', 'sight', 'Chen Clan Ancestral Hall (Guangdong Folk Arts Museum)', '陈氏书院（广东民间工艺博物馆）', 'Liwan', '荔湾区',
        '广州市荔湾区中山七路恩龙里34号', 'https://www.amap.com/place/B00140H88E', true,
        'Official hours are 09:00–17:30 with 17:00 last entry. Booking required — purchase seven timed tickets through WeChat account 广东民间工艺博物馆服务号 via 门票购买. Official museum site: https://www.gzcjc.com.cn/',
        '开放时间09:00–17:30，17:00停止入场。需预约——通过微信公众号"广东民间工艺博物馆服务号"的"门票购买"购买七张分时门票。官网：https://www.gzcjc.com.cn/'),
      itemB('12:30', 'meal', 'Yin Ji Rice Noodle Rolls (Wenchang North Road Branch)', '银记肠粉（文昌北路店）', 'Liwan', '荔湾区',
        '广州市荔湾区文昌北路345号之一、之二、之三首层', 'https://www.amap.com/place/B0FFFPKJL5', false,
        'Super famous Wenchang shop since 1958 — exceptionally thin, soft rice sheets; beef and egg rice rolls are practical fast orders.',
        '1958年至今的文昌名店——粉皮极薄嫩滑；牛肉肠、鸡蛋肠出餐快，实惠好点。'),
      itemB('13:30–16:30', 'sight', 'Shamian Island', '沙面岛', 'Liwan', '荔湾区',
        '广州市荔湾区沙面岛', 'https://www.amap.com/place/B00140NZ25', false,
        'Former foreign-concession island layers European façades onto the Pearl River.',
        '旧租界小岛，欧式建筑立面与珠江景致相映。', [
        nearB('restaurant', 'Starbucks Reserve Guangzhou Shamian', '星巴克臻选（广州沙面店）',
          'Air-conditioned break.',
          '有空调，歇歇脚。',
          '广州市荔湾区沙面大街50-52号', 'https://www.amap.com/place/B00140NZ8T'),
        nearB('restaurant', 'HEYTEA Guangzhou Shamian DP', '喜茶广州沙面DP店',
          'About 5 minutes away in a heritage building. Order at the counter or through the 喜茶 WeChat mini-program after selecting 广州沙面DP店; check seasonal Cantonese-dessert-inspired drinks.',
          '约5分钟路程，开在历史建筑里。柜台点单，或在喜茶微信小程序选"广州沙面DP店"下单；留意粤式甜品灵感的季节限定。',
          '广州市荔湾区沙面大街49号首层', 'https://www.amap.com/place/B0M63LAK9M'),
      ]),
      itemB('18:00', 'meal', 'Flexible Dinner Option', '灵活晚餐', 'Liwan', '荔湾区',
        '广州市荔湾区恩宁路99号', 'https://www.amap.com/place/B0IUPDSJHU', false,
        'Open to anything around here; chill out until sunset and see the trendy Yongqingfang district at night.',
        '这附近吃什么都行；悠闲待到日落，晚上再逛时髦的永庆坊。'),
      itemB('19:00', 'sight', 'Yongqingfang & Enning Road Evening Walk', '永庆坊·恩宁路夜游', 'Liwan', '荔湾区',
        '广州市荔湾区恩宁路99号', 'https://www.amap.com/place/B0IUPDSJHU', false,
        'Very atmospheric district after dark — focus on the Enning Road arcades, canal lighting and courtyards. Open to anything here until back to the hotel; going out on an expedition tomorrow to see the Seven Star Crags.',
        '入夜后氛围极佳——重点看恩宁路骑楼、涌边灯光与院落。玩到尽兴再回民宿；明天远行去看七星岩。', [
        nearB('restaurant', 'Red Door Coffee', '红门咖啡',
          'Cool alcoholic coffee drinks sold here.',
          '有特调含酒精咖啡。',
          '广州市荔湾区多宝路多宝坊涌边1号(粤剧博物馆核算采样点隔壁)', 'https://www.amap.com/place/B0JBSZR5CW'),
      ]),
    ]),
    day('Jul 28', 'Tue', 'Star Lake & Karst Peaks', '星湖与喀斯特峰林', [
      itemB('06:30–07:45', 'transit', 'Transit to Panyu Intercity Station', '前往番禺城际站', 'Yuexiu–Panyu', '越秀—番禺',
        '番禺城际站', 'https://www.amap.com/place/B0KD55VY6C', false,
        'Take Metro Line 2 from Gongyuanqian to Guangzhou South and then to Panyu Station. Use two Didi vehicles as the late-departure or rain fallback. Every traveler should complete Guangdong Intercity identity and payment setup before this morning.',
        '从公园前乘地铁2号线到广州南站，再到番禺站。若出发晚或下雨，则分乘两辆滴滴。所有人应在今早之前完成广东城际的实名与支付设置。'),
      itemB('08:00–09:00', 'transit', 'Guangdong Intercity to Zhaoqing Station', '广东城际前往肇庆站', 'Panyu–Zhaoqing', '番禺—肇庆',
        '番禺城际站 → 肇庆站；具体车次及站台', 'https://www.amap.com/place/B0KD55VY6C', false,
        'Use a direct train scheduled to arrive around 09:00. Guangdong Intercity operates with metro-style boarding rather than advance reservations. Ticketing guidance: https://www.gz.gov.cn/zwfw/zxfw/jtfw/content/post_9650883.html',
        '选约09:00到达的直达车次。广东城际类似地铁随到随走，无需提前订座。购票指南：https://www.gz.gov.cn/zwfw/zxfw/jtfw/content/post_9650883.html'),
      itemB('09:00–09:30', 'transit', 'Didi to Seven Star Crags North Gate', '前往七星岩北门', 'Zhaoqing', '肇庆市',
        '七星岩景区(北门)', 'https://www.amap.com/place/B02F60P72K', false,
        'Use two Didis to the North Gate before admission.',
        '分乘两辆滴滴到北门，再购票入园。'),
      itemB('09:30–14:30', 'sight', 'Seven Star Crags Moderate Scenic Circuit', '七星岩中等强度山水环线', 'Duanzhou, Zhaoqing', '肇庆端州区',
        '肇庆市端州区七星岩景区北门（肇庆大道辅路附近）', 'https://www.amap.com/place/B02F60P72K', true,
        'North Gate → Tianzhu Rock Summit → Shishi Rock → Shuiyue Palace → archway-side exit. Official scenic-area guide: https://t.xhglj.com.cn/pwzn/index.shtml. Skip Tianzhu Rock when wet or stormy. Lunch after.',
        '北门→天柱岩→石室岩→水月宫→牌坊侧出口。官方游览指南：https://t.xhglj.com.cn/pwzn/index.shtml。雨天或雷雨时跳过天柱岩。下山后吃午餐。'),
      itemB('16:30', 'transit', 'Didi to Zhaoqing Station', '前往肇庆站', 'Zhaoqing', '肇庆市',
        '肇庆站', 'https://www.amap.com/search?query=' + encodeURIComponent('肇庆站'), false,
        'For the 16:30–17:30 Guangdong Intercity back to Panyu, then return to our hotel. Keep dinner flexible around the hotel since we had a late lunch.',
        '乘16:30–17:30的广东城际返回番禺，再回民宿。午餐吃得晚，晚餐就在民宿附近灵活解决。'),
      itemB('19:30', 'meal', 'Flexible Light Beijing Road Dinner', '北京路灵活轻食晚餐', 'Beijing Road', '北京路',
        '广州市越秀区惠福东路452号', 'https://www.amap.com/place/B0FFLI77QK', false,
        'Preference: Min Ji Claypot Rice (Beijing Road Branch). Or wander Huifu Gourmet and Flower Street / 惠福美食花街 — lots of Cantonese snacks and long-standing restaurants (惠福东路, from 禺山路 west to No. 470; pick whichever is currently open).',
        '首选Min Ji煲仔饭（北京路店）；或逛惠福美食花街——粤式小吃与老字号云集（惠福东路，东起禺山路、西至惠福东路470号；选当前营业的商户）。'),
      itemB('21:00', 'wellness', 'Chinese Full-body Massage', '中式全身推拿', 'Beijing Road', '北京路',
        '北京路（民宿附近）', 'https://www.amap.com/search?query=' + encodeURIComponent('北京路 按摩'), true,
        'Check on the apps for a place close to our hotel to get a full-body massage.',
        '在大众点评等App上找一家离民宿近的全身推拿。'),
    ]),
    day('Jul 29', 'Wed', 'Farewell Tea & the Five Rams', '告别早茶·五羊', [
      itemB('08:30', 'meal', 'Tao Tao Ju (Beijing Road Branch)', '陶陶居酒家（北京路店）', 'Beijing Road', '北京路',
        '广州市越秀区北京路102–168号北京路天河城7楼707–708号商铺', 'https://www.amap.com/search?query=' + encodeURIComponent('陶陶居 北京路天河城'), true,
        'The brand dates to 1880 and is a Guangzhou dim-sum institution; prioritize shrimp dumplings, roast specialties and flaky pastries. Locations: https://www.taotaoju1880.com/zoujintaotaoju/taotaojumendian',
        '品牌创于1880年，是广州早茶老字号；主攻虾饺、烧味与酥点。门店信息：https://www.taotaoju1880.com/zoujintaotaoju/taotaojumendian'),
      itemB('09:30', 'sight', 'Yuexiu Park: Five Rams & Zhenhai Tower', '越秀公园·五羊石像·镇海楼', 'Yuexiu', '越秀区',
        '广州市越秀区解放北路960号；西门进（西门→五羊石像→明城墙→镇海楼）', 'https://www.amap.com/place/B00140T14M', false,
        'The West-gate route links Guangzhou’s Five Rams statue, the surviving Ming city wall and the 1380 Zhenhai Tower; expect hills and stairs.',
        '西门线路串起五羊石像、明代古城墙与1380年落成的镇海楼；有坡道和台阶。', [
        nearB('sight', 'Sun Yat-sen Memorial Hall (South Gate)', '中山纪念堂（南门）',
          'The 1931 memorial hall celebrating the founding father of modern China.',
          '1931年落成，纪念中国近代革命先行者孙中山先生。',
          '广州市越秀区东风中路259号', 'https://www.amap.com/place/B00140TFUN'),
      ]),
      itemB('13:00', 'admin', 'Collect Luggage & Check Out', '取行李并退房', 'Beijing Road', '北京路',
        GZ_HOTEL_ADDR, GZ_HOTEL_MAP, false,
        'Dependent on whether we secured late checkout or the host can store our bags for us.',
        '取决于是否争取到延迟退房，或房东能否帮忙寄存行李。'),
      itemB('16:30', 'transit', 'Flight to Shanghai — Guangzhou Baiyun International Airport', '飞往上海·广州白云国际机场', 'Baiyun District', '白云区',
        GZ_AIRPORT_ADDR, GZ_AIRPORT_MAP, false,
        'Flight to Shanghai; arrive 2 hours early for domestic flights.',
        '飞往上海；国内航班请提前2小时到达机场。'),
    ]),
  ],
};

// ============================ SHANGHAI ============================
// Real finalized itinerary. Addresses & Amap links verbatim.

const SH_HOTEL_ADDR = '上海市静安区巨鹿路光华里(静安寺地铁站8号口步行350米)';
const SH_HOTEL_MAP = 'https://www.amap.com/place/B0J3TBDL86';

const shanghai = {
  id: 'sh',
  name: { en: 'Shanghai', zh: '上海' },
  dateRange: 'Jul 29 – Aug 2',
  hotel: {
    name: { en: 'Linju Homestay (Jing’an Temple Branch)', zh: '柃居民宿(静安寺店)' },
    address: { text: SH_HOTEL_ADDR, mapUrl: SH_HOTEL_MAP },
    phone: '+86 136 5172 8077 / +86 136 0620 9930', confirmation: '1227103893421544',
    checkIn: { time: '14:00', note: { en: 'Message the host with your expected arrival time for the exact unit and check-in instructions.', zh: '请提前告知房东预计到达时间，获取具体房号与入住指引。' } },
    checkOut: { time: '12:00', note: { en: 'Confirm luggage storage with the host if needed.', zh: '如需寄存行李，请与房东确认。' } },
    wifi: { en: 'Premium Wi-Fi included, no password', zh: '包含高级 Wi-Fi，无需密码' },
    notes: [
      { en: '350 m walk from Jing’an Temple Metro Exit 8', zh: '距静安寺地铁站8号口步行350米' },
    ],
  },
  mustEats: [
    { name: { en: 'Xiaolongbao', zh: '小笼包' }, note: { en: 'Soup dumplings', zh: '汤汁小笼' } },
    { name: { en: 'Pan-fried Buns', zh: '生煎包' }, note: { en: 'Crispy bottoms', zh: '脆底多汁' } },
    { name: { en: 'Red-braised Pork', zh: '红烧肉' }, note: { en: 'Sweet & savory', zh: '浓油赤酱' } },
    { name: { en: 'Scallion Oil Noodles', zh: '葱油拌面' }, note: { en: 'Simple & fragrant', zh: '香气扑鼻' } },
    { name: { en: 'Hairy Crab', zh: '大闸蟹' }, note: { en: 'Seasonal treat', zh: '应季美味' } },
    { name: { en: 'Shanghai Wontons', zh: '上海馄饨' }, note: { en: 'Light & comforting', zh: '清淡暖胃' } },
    { name: { en: 'Sweet-and-sour Ribs', zh: '糖醋小排' }, note: { en: 'Tangy Shanghai classic', zh: '本帮酸甜' } },
  ],
  days: [
    day('Jul 29', 'Wed', 'Arrival', '抵达', [
      itemB('19:00', 'transit', 'Arrival & Homestay Check-in', '抵达并办理民宿入住', 'Jing’an', '静安区',
        SH_HOTEL_ADDR, SH_HOTEL_MAP, false,
        'Compare Didi with public transit after landing and message the host with the expected arrival time and exact unit/check-in instructions.',
        '落地后比较滴滴与公共交通，并给房东发消息告知预计到达时间，确认具体房号与入住指引。'),
      itemB('21:00', 'meal', 'Flexible Late Supper in the Julu–Anfu Lanes', '巨鹿路—安福路灵活夜宵', 'Jing’an', '静安区',
        'Julu Road / Anfu Road / Yongfu Road  巨鹿路 / 安福路 / 永福路', 'https://www.amap.com/search?query=' + encodeURIComponent('上海 安福路'), false,
        'Flexible late supper; Shanghainese noodles, dumplings, or Yunnan small plates.',
        '灵活夜宵；本帮面、饺子或云南小馆都可以。', [
        nearB('restaurant', 'Haidilao (Beijing West Road Night-Snack Branch)', '海底捞火锅（北京西路夜宵主题店）',
          'Short taxi; call after landing or join the live queue for one table of seven.',
          '打车片刻即到；落地后致电或现场排队，订一桌七人。',
          '上海市静安区北京西路1068号食博汇3层', 'https://www.amap.com/place/B0FFHK5T7L'),
        nearB('restaurant', 'Jiu Jiu Di Shui Dong (South Maoming Road)', '久久滴水洞（茂名南路店）',
          'Hunan option with late-meal options; check last order time on Dianping.',
          '湘菜深夜选择；在大众点评确认最晚点餐时间。',
          '上海市黄浦区茂名南路56号2层', 'https://www.amap.com/place/B0FFFXYFK4'),
      ]),
    ]),
    day('Jul 30', 'Thu', 'Jing’an & the French Concession', '静安与法租界', [
      itemB('08:00', 'meal', 'Neighborhood Shanghai Breakfast', '上海街坊早餐', 'Julu Road', '巨鹿路',
        '上海市静安区巨鹿路（民宿附近）', SH_HOTEL_MAP, false,
        'Try nearby Shanghai staples such as sticky-rice rolls / 粢饭团, scallion-oil noodles / 葱油拌面, and soy milk with youtiao / 豆浆油条.',
        '尝尝附近的上海经典早点：粢饭团、葱油拌面、豆浆油条。'),
      itemB('08:30', 'sight', 'Jing’an Temple', '静安寺', 'Jing’an', '静安区',
        '上海市静安区南京西路1686号', 'https://www.amap.com/place/B00155GX2S', false,
        'Visit early before crowds build; buy admission at the entrance.',
        '趁人流未起早点参观；门票在入口处购买。'),
      itemB('10:30', 'sight', 'Wukang Building & Anfu Road Walk', '武康大楼及武康路—安福路漫步', 'Wukang Road–Anfu Road', '武康路—安福路',
        '上海市徐汇区淮海中路1850号', 'https://www.amap.com/place/B00155ITJ1', false,
        'Allow roughly 20–35 minutes from Jing’an Temple. Photograph the residential building from outside, then continue north along Wukang Road toward Ferguson Lane and Anfu Road.',
        '从静安寺过来约20–35分钟。在外面拍摄这座住宅大楼，然后沿武康路向北，经武康庭走到安福路。', [
        nearB('shopping', 'Deja Vu Recycle Store', '多抓鱼循环商店',
          'Shanghai resale shop for secondhand clothing and books.',
          '上海的二手衣物与图书循环商店。',
          '上海市徐汇区安福路300号（近武康路）', 'https://www.amap.com/place/B0FFJQXV01'),
        nearB('restaurant', 'Kukuang Ice Cream (Wukang Building Shop)', '酷矿冰淇淋（武康大楼店）',
          'At the Wukang Building itself; sculpted seasonal soft-serve is the photogenic specialty.',
          '就在武康大楼底楼；造型雪糕与季节限定软冰是出片招牌。',
          '上海市徐汇区淮海中路1852号武康大楼底楼', 'https://www.amap.com/place/B0FFKSCPJF'),
      ]),
      itemB('12:30', 'meal', 'Lunch at Jianguo 328', '建国328小馆', 'Xuhui', '徐汇区',
        '上海市徐汇区建国西路326–328号', 'https://www.amap.com/place/B00156FLJS', true,
        'Call ahead and request one table for seven because the dining room is small; a compact choice for homestyle Shanghai cuisine.',
        '店面很小，提前致电订一桌七人；家常本帮菜的紧凑好选择。', [
        nearB('restaurant', 'Qiaojiazha Restaurant', '乔家栅食府',
          'Time-honored Shanghai sweets, glutinous-rice dumplings, and eight-treasure rice.',
          '老字号上海甜点、汤团与八宝饭。',
          '上海市徐汇区襄阳南路336号', 'https://www.amap.com/place/B00151524C'),
        nearB('shopping', 'IAPM Mall', '环贸iapm商场',
          'Large Chinese mega mall, but not walk-next-door: allow roughly 8–12 minutes by taxi.',
          '大型商场，但不是隔壁就到：打车约8–12分钟。',
          '上海市徐汇区淮海中路999号', 'https://www.amap.com/place/B00156GS83'),
      ]),
      itemB('14:00–17:00', 'activity', 'French Concession Flexible Exploration', '衡复风貌区灵活探索', 'French Concession', '衡复风貌区',
        '上海田子坊', 'https://www.amap.com/place/B00155HO6Y', false,
        'Book Long Time Ago Skewers while doing this. Suggested route: Wukang Mansion → Soong Ching-ling’s Former Residence → Wulumuqi Middle Road → Anfu Road → Wuyuan Road → Changle Road & Donghu Road → Cathay Cinema & Maoming South Road → Fuxing Park → Sinan Mansions & Sinan Road → Xintiandi → Tianzifang.',
        '逛的同时记得给"很久以前羊肉串"取号。建议路线：武康大楼 → 宋庆龄故居 → 乌鲁木齐中路 → 安福路 → 五原路 → 长乐路/东湖路 → 国泰电影院/茂名南路 → 复兴公园 → 思南公馆/思南路 → 新天地 → 田子坊。', [
        nearB('restaurant', 'mimilato (Xuhui Yipinyuan Shop)', 'mimilato（徐汇一品苑店）',
          'Creative gelato includes seasonal fruit, pistachio, herbs, and savory-leaning flavors. The shop is very small, so order takeaway for seven.',
          '创意gelato：时令水果、开心果、香草及偏咸口味。店面很小，七人建议外带。',
          '上海市徐汇区长乐路与镇宁路交叉口东40米', 'https://www.amap.com/place/B0IGMRD2Q9'),
        nearB('restaurant', 'BUTTERFUL & CREAMOROUS (Xintiandi Style Shop)', 'B&C黄油与面包·法式古堡面包坊（新天地时尚店）',
          'Flashy French-style croissants, cream puffs, and photogenic pastries.',
          '吸睛的法式牛角包、奶油泡芙与适合拍照的烘焙。',
          '上海市黄浦区自忠路与黄陂南路交叉口西60米', 'https://www.amap.com/place/B0IA3OFIBC'),
      ]),
      itemB('18:00', 'meal', 'Long Time Ago Mutton Skewers (818 Plaza Branch)', '很久以前羊肉串（南京西路818广场店）', 'Jing’an', '静安区',
        '上海市静安区南京西路818广场B1层B102a、B102b商铺（王家沙对面）', 'https://www.amap.com/place/B0LCSZTJMA', true,
        'Take a remote queue number around 16:30–17:00 through Dianping.',
        '16:30–17:00左右通过大众点评线上取号。', [
        nearB('shopping', 'HKRI Taikoo Hui', '兴业太古汇',
          'Air-conditioned shopping, opposite the 818 Plaza cluster.',
          '有空调的商场，就在818广场对面。',
          '上海市静安区石门一路288号', 'https://www.amap.com/place/B0FFG8S5RN'),
        nearB('restaurant', 'AHMA Handmade (HKRI Taikoo Hui Shop)', '阿嬷手作（兴业太古汇店）',
          'About 3–6 minutes on foot after skewers; handmade rice-mochi drinks, thick steamed taro, and milk drinks. Mobile-order the seven drinks together to reduce the pickup wait.',
          '吃完串步行约3–6分钟；手作麻薯饮品、浓郁蒸芋头与奶制饮品。七杯一起线上下单可减少取餐等待。',
          '上海市静安区南京西路789号兴业太古汇LG1层LG172-LG174商铺', 'https://www.amap.com/place/B0K3CRDYXC'),
      ]),
    ]),
    day('Jul 31', 'Fri', 'Old City, East Nanjing & Rockbund', '老城厢·南京东路·外滩源', [
      itemB('08:00', 'meal', 'Dingxing Road Egg Pancake Stall', '定兴路蛋饼摊', 'Huangpu', '黄浦区',
        '上海市黄浦区定兴路1号（人民广场地铁站14号口步行270米）', 'https://www.amap.com/place/B0K2SB14J0', false,
        'Optional Shanghai breakfast; use another nearby breakfast if the stall is closed or the queue is too long.',
        '可选的上海早餐；若摊位没开或排队太长，就改吃附近其他早点。', [
        nearB('sight', 'People’s Square', '人民广场',
          'Large civic plaza.',
          '大型市政广场。',
          '上海市黄浦区人民大道185号', 'https://www.amap.com/place/B00157917M'),
        nearB('restaurant', 'Jia Jia Tang Bao (Huanghe Road Branch)', '佳家汤包（黄河路店）',
          'Popular soup dumplings; expect a live queue and go early if using it as breakfast.',
          '人气汤包；需现场排队，当早餐吃要趁早。',
          '上海市黄浦区黄河路127号（人民广场地铁站8号口步行340米）', 'https://www.amap.com/place/B0GRUR6E73'),
      ]),
      itemB('09:00', 'sight', 'Yu Garden', '上海豫园', 'Old City · Yuyuan', '老城厢·豫园',
        '上海市黄浦区福佑路168号', 'https://www.amap.com/place/B00155KLUC', true,
        'Allow 10–20 minutes for entry. The classical garden is ticketed; the surrounding bazaar is free. Buy onsite or through the official “上海豫园” WeChat channel.',
        '入园预留10–20分钟。古典园林需购票，周边商城免费。可现场购票或通过官方"上海豫园"微信渠道购买。'),
      itemB('10:30', 'sight', 'Shanghai City God Temple', '上海城隍庙', 'Old City · Yuyuan', '老城厢·豫园',
        '上海市黄浦区方浜中路249号', 'https://www.amap.com/place/B00155FHOA', false,
        'Visit the active Taoist temple for roughly 30–45 minutes.',
        '参观这座香火旺盛的道教庙宇，约30–45分钟。'),
      itemB('12:00', 'meal', 'Da Hu Chun (Middle Sichuan Road Branch)', '大壶春（四川中路店）', 'East Nanjing · Middle Sichuan Road', '南京东路·四川中路',
        '上海市黄浦区四川中路136号（近广东路）', 'https://www.amap.com/place/B0FFGJN697', false,
        'Casual lunch centered on traditional pan-fried pork buns; allow 45–55 minutes and join the live queue if needed. After lunch, return to the People’s Square end of East Nanjing Road for shopping.',
        '以传统生煎为主的简餐；预留45–55分钟，需要时现场排队。饭后回到南京东路靠人民广场一端开始逛街。'),
      itemB('13:30', 'shopping', 'East Nanjing Road Chinese-brand Browsing', '南京东路国货浏览', 'East Nanjing Road', '南京东路',
        '上海市黄浦区南京东路558号南京路步行街西口', 'https://www.amap.com/place/B0FFF4MDU1', false,
        'Start at the People’s Square end and walk east toward Bailian ZX, browsing Chinese brands along the way.',
        '从人民广场一端出发向东走到百联ZX，一路浏览国货品牌。', [
        nearB('shopping', 'ANTA (New World City Branch)', '安踏（新世界城店）',
          'Chinese performance footwear and apparel.',
          '国产运动鞋服。',
          '上海市黄浦区南京西路2–88号新世界城6楼（人民广场地铁站7号口旁）', 'https://www.amap.com/place/B00156F1SL'),
        nearB('restaurant', 'Shen Dacheng (Gangtai Plaza)', '沈大成(港泰广场店)',
          'Shanghai pastry and snack option since 1875.',
          '创于1875年的上海糕点与小吃。',
          '上海市黄浦区延安东路700号港泰广场F1层', 'https://www.amap.com/place/B0J12D56RK'),
        nearB('restaurant', 'CHAGEE (Zhongfucheng Shop)', '霸王茶姬（中福城店）',
          'About 3–6 minutes off the East Nanjing walk. Mobile-order for seven and collect.',
          '离南京东路步行约3–6分钟。七杯线上下单后自取。',
          '上海市黄浦区浙江中路210号底层', 'https://www.amap.com/place/B0JUTHHLRE'),
      ]),
      itemB('15:00', 'shopping', 'Bailian ZX Creative Center', '百联ZX创趣场', 'East Nanjing Road', '南京东路',
        '上海市黄浦区南京东路340–372号', 'https://www.amap.com/place/B00155HPWC', false,
        'Shanghai’s Akihabara. B1 Indie & Underground, 1F Premium Collectibles, 2F Gaming & Lifestyle, 3F TCG Zone, 4F Anime Goods, 5F Dining, 6F Popup Events.',
        '上海的"秋叶原"。B1独立与地下文化，1F高端收藏，2F游戏与生活方式，3F集换式卡牌区，4F动漫周边，5F餐饮，6F快闪活动。'),
      itemB('17:00', 'sight', 'Rockbund Art Museum', '上海外滩美术馆', 'Rockbund', '外滩源',
        '上海市黄浦区虎丘路20号（主入口在虎丘路东侧博物院广场）', 'https://www.amap.com/place/B00155QH3P', false,
        'Friday admission is currently free. Check the current exhibition before going: https://www.rockbundartmuseum.org/visit',
        '目前周五免票。出发前先查看当前展览：https://www.rockbundartmuseum.org/visit'),
      itemB('18:00', 'meal', 'Flexible Dinner in Rockbund', '外滩源灵活晚餐', 'Rockbund', '外滩源',
        '上海市黄浦区圆明园路—虎丘路街区', 'https://www.amap.com/place/B0FFF3LKUB', false,
        'Choose dinner within the Rockbund cluster; afterward, stay for skyline views.',
        '在外滩源街区内选一家吃晚餐；饭后留下来看天际线夜景。'),
    ]),
    day('Aug 1', 'Sat', 'Chinese Design Shopping & Riverfront Ride', '中国设计购物与滨江骑行', [
      itemB('09:00–13:00', 'shopping', 'Huaihai Chinese Design Shopping', '淮海路中国设计购物线', 'Huaihai Middle Road', '淮海中路',
        '上海市黄浦区淮海中路523号', 'https://www.amap.com/place/B00150C2E4', false,
        'TX Huaihai, MASONPRINCE and HAI550 — mostly local Chinese brands. Can split up based on our shopping preferences here and regroup later. Finish around 13:00 for lunch.',
        'TX淮海、MASONPRINCE与HAI550——以本土品牌为主。可按各自喜好分头逛，稍后集合。约13:00结束去吃午餐。', [
        nearB('shopping', 'MASONPRINCE Shanghai Flagship', 'MASONPRINCE上海旗舰店',
          'Core local-brand stop in Hehefang; men’s and women’s streetwear.',
          '和合坊里的核心本土品牌；男女街头潮流服饰。',
          '上海市黄浦区淮海中路526弄之1-84号和合坊', 'https://www.amap.com/place/B0JK0ZQM8L'),
        nearB('shopping', 'Shanghai K11 Art Mall', '上海K11购物艺术中心',
          'Art-led retail about 5–10 minutes east on foot.',
          '艺术主题商场，向东步行约5–10分钟。',
          '上海市黄浦区淮海中路300号', 'https://www.amap.com/place/B00155HOU9'),
        nearB('sight', 'Site of the First National Congress of the CPC', '中共一大会址',
          'Historic shikumen site nearby; exterior viewing is easy, while museum entry follows separate access rules.',
          '附近的历史石库门建筑；看外观很方便，入馆参观须遵循另行的预约规则。',
          '上海市黄浦区黄陂南路374号', 'https://www.amap.com/place/B0MGOCVPM6'),
      ]),
      itemB('13:30', 'meal', 'Lunch at Wu You Xian', '屋有鲜', 'Huaihai–South Maoming Road', '淮海中路·茂名南路',
        '上海市黄浦区茂名南路7号1F-103室', 'https://www.amap.com/place/B0LMM4JY98', true,
        'Michelin Guide-listed soup-dumpling specialist known for crab fillings; contact the restaurant ahead about seating seven because quantities and space are limited.',
        '米其林指南推荐的汤包专门店，以蟹粉馅闻名；数量与座位有限，提前联系餐厅确认七人就座。', [
        nearB('sight', 'Cathay Cinema (Huaihai Middle Road)', '国泰电影院（淮海中路店）',
          'Photograph the 1932 Art Deco cinema exterior.',
          '拍摄这座1932年装饰艺术风格影院的外立面。',
          '上海市黄浦区淮海中路870号', 'https://www.amap.com/place/B00155Q6V1'),
      ]),
      itemB('16:00', 'admin', 'Drop Off Shopping at the Homestay', '回民宿放下购物品', 'Jing’an', '静安区',
        SH_HOTEL_ADDR, SH_HOTEL_MAP, false,
        'Drop purchases, change, hydrate, and charge devices before leaving for the Bund.',
        '放下购物品、换身衣服、补水、给设备充电，再出发去外滩。'),
      itemB('18:00', 'meal', 'Flexible Dinner near Waibaidu Bridge', '外白渡桥附近灵活晚餐', 'Rockbund–Waibaidu', '外滩源—外白渡桥',
        '上海市黄浦区圆明园路—北苏州路片区', 'https://www.amap.com/search?query=' + encodeURIComponent('上海 圆明园路 北苏州路'), false,
        'Choose somewhere that can seat seven promptly and finish by about 19:00; avoid a detour so the group can reach the bike-start area by 19:30.',
        '选一家能马上坐下七人的餐厅，约19:00前吃完；不要绕路，确保全组19:30前到达骑行起点。'),
      itemB('19:30', 'activity', 'Huangpu Riverfront Greenway Bike Ride: Waibaidu Bridge to Rihuigang', '黄浦滨江绿道：外白渡桥至日晖港桥', 'Huangpu Riverfront', '黄浦滨江',
        '上海市黄浦区中山东一路33号英国领事馆及领事官邸旧址内', 'https://www.amap.com/place/B00156R4JP', false,
        'Start somewhere near the map pin. Use Hellobike (blue), Meituan Bike (yellow), or Qingju Bike (green) — blue is easiest, just scan the QR with Alipay. 8.3 km ride, 50–60 minutes along the Bund. Details: https://english.shanghai.gov.cn/en-Fitness/20250909/778da0db22d547e5943c90ed3b683331.html',
        '在地图标记附近出发。可用哈啰（蓝）、美团（黄）或青桔（绿）单车——蓝色最方便，用支付宝扫码即可。沿外滩骑行8.3公里，约50–60分钟。详情：https://english.shanghai.gov.cn/en-Fitness/20250909/778da0db22d547e5943c90ed3b683331.html'),
    ]),
    day('Aug 2', 'Sun', 'Shanghai Departure', '离开上海', [
      itemB('09:30', 'transit', 'Flight to Beijing Capital International Airport (PEK)', '飞往北京首都国际机场', 'Changning', '长宁区',
        '上海市长宁区虹桥路2550号上海虹桥国际机场', 'https://www.amap.com/place/B001559TVX', false,
        '09:30 is the scheduled departure time; confirm the airline and terminal, leave the hotel early enough for check-in and security, and verify Steven’s separate Beijing airport DMV appointment.',
        '09:30为计划起飞时间；确认航空公司与航站楼，提早离开民宿以便值机和安检，并核实Steven在北京机场另行办理的车管所预约。'),
    ]),
  ],
};

// ============================ BEIJING ============================
// Real finalized itinerary (source: FinalizedBeijing.md). Addresses & Amap links verbatim.

const BJ_HOTEL_ADDR = '北京市朝阳区工人体育场北路21号爱奇艺青春中心F5层';
const BJ_HOTEL_MAP = 'https://www.amap.com/place/B0K2HAEXUI';
const BJ_AIRPORT_ADDR = '北京市朝阳区首都机场路11号';
const BJ_AIRPORT_MAP = 'https://www.amap.com/place/B000A28DAE';
const nearTheBox = nearB('shopping', 'THE BOX Chaowai Young Power Center', 'THE BOX 朝外|年轻力中心',
  'About 10–15 min away; youth-culture retail, streetwear, exhibitions, and photogenic interiors.',
  '约10–15分钟路程；青年文化零售、街头潮牌、展览与出片的室内空间。',
  '北京市朝阳区朝外大街12号', 'https://www.amap.com/place/B0IRRUF3C1');
const nearXiadu = nearB('activity', 'Xiadu Park', '夏都公园',
  'About 20–30 minutes by car on the onward route; lakeside paths and public sculpture.',
  '顺路驾车约20–30分钟；湖畔步道与公共雕塑。',
  '北京市延庆区湖北西路2号', 'https://www.amap.com/place/B000A52109');

const beijing = {
  id: 'bj',
  name: { en: 'Beijing', zh: '北京' },
  dateRange: 'Aug 2 – 6',
  hotel: {
    name: { en: 'Miyue LOFT Duplex Homestay — Sanlitun Workers’ Stadium', zh: '复式|蜜悦民宿(三里屯·工人体育场地铁站店)' },
    address: { text: BJ_HOTEL_ADDR, mapUrl: BJ_HOTEL_MAP },
    phone: '+86 185 1111 1664', confirmation: '1227103978064815',
    checkIn: { time: '14:00', note: { en: 'Add the housekeeper’s WeChat (+86 185 1111 1664) for the host meet-up at Building 21.', zh: '请添加管家微信（+86 185 1111 1664），在21号楼与房东会合。' } },
    checkOut: { time: '12:00', note: { en: 'Confirm bag storage until 16:30.', zh: '确认行李可寄存至16:30。' } },
    wifi: { en: 'Premium Wi-Fi included, no password', zh: '包含高级 Wi-Fi，无需密码' },
    notes: [
      { en: 'See the Check-In Guide for directions to the entrance', zh: '入口路线请参见入住指南' },
      { en: 'Confirm overnight parking for the rental car', zh: '确认租车的过夜停车安排' },
      { en: 'Massage booking', zh: '预约按摩' },
    ],
    nearby: [
      nearTheBox,
      nearB('sight', 'Beijing Dongyue Temple', '北京东岳庙',
        'About 10 minutes by transit; a distinctive Taoist temple complex with folk-culture displays.',
        '乘车约10分钟；独具特色的道教庙宇建筑群，设有民俗文化展。',
        '北京市朝阳区朝阳门外大街141号', 'https://www.amap.com/place/B000A7HEUS'),
      nearB('sight', 'Beijing Workers’ Stadium', '北京工人体育场',
        'About 5–10 minutes on foot; circle the rebuilt stadium exterior and check event-day access before setting out.',
        '步行约5–10分钟；可绕行新工体外围，出发前请确认赛事日的通行安排。',
        '北京市朝阳区工人体育场北路1号', 'https://www.amap.com/place/B000A7CJLQ'),
      nearB('shopping', 'Sanlitun SOHO Centre', '三里屯SOHO商场',
        'About 10–15 minutes on foot; use the plaza for casual food, convenience shopping, and a low-commitment evening wander.',
        '步行约10–15分钟；广场适合简餐、便利购物和轻松的夜间闲逛。',
        '北京市朝阳区工人体育场北路8号三里屯soho', 'https://www.amap.com/place/B0LRN6L0H1'),
    ],
  },
  mustEats: [
    { name: { en: 'Peking Duck', zh: '北京烤鸭' }, note: { en: 'Crisp & carved tableside', zh: '脆皮现片' } },
    { name: { en: 'Zhajiangmian', zh: '炸酱面' }, note: { en: 'Savory bean-paste noodles', zh: '酱香拌面' } },
    { name: { en: 'Jianbing', zh: '煎饼' }, note: { en: 'Breakfast crepe', zh: '街头早餐' } },
    { name: { en: 'Copper-pot Hot Pot', zh: '铜锅涮肉' }, note: { en: 'Lamb & sesame sauce', zh: '涮羊配麻酱' } },
    { name: { en: 'Douzhi', zh: '豆汁' }, note: { en: 'For the adventurous', zh: '老北京风味' } },
    { name: { en: 'Candied Hawthorn', zh: '冰糖葫芦' }, note: { en: 'Sweet-tart skewer', zh: '酸甜串子' } },
    { name: { en: 'Fried Liver Stew', zh: '炒肝' }, note: { en: 'Garlicky classic breakfast', zh: '蒜香浓稠，老北京早点' } },
  ],
  days: [
    day('Aug 2', 'Sun', 'Arrival, Sanlitun, Peking Duck, Rest', '抵达·三里屯·烤鸭·休整', [
      itemB('12:00', 'transit', 'Arrival — Beijing Capital International Airport', '抵达·北京首都国际机场', 'Shunyi', '顺义区',
        BJ_AIRPORT_ADDR, BJ_AIRPORT_MAP, false,
        'Domestic flight from Shanghai; compare taxi vs transit price and time. No rush today.',
        '从上海乘国内航班抵达；比较打车与公共交通的价格和时间。今天不赶时间。'),
      itemB('13:30', 'admin', 'Check in to Hotel', '办理酒店入住', 'Chaoyang', '朝阳区',
        BJ_HOTEL_ADDR, BJ_HOTEL_MAP, false,
        'Check in, and drop bags at the room if it isn’t ready yet.',
        '办理入住；如房间尚未备好，先寄存行李。'),
      itemB('15:00', 'shopping', 'Explore Taikoo Li Sanlitun Mall', '三里屯太古里', 'Chaoyang', '朝阳区',
        '北京市朝阳区三里屯路11、19号院(工人体育场地铁站D口步行240米)', 'https://www.amap.com/place/B0FFFT5A1C', false,
        'Browse the open-air fashion district, have some snacks, get ready for dinner, chill.',
        '逛逛露天时尚街区，吃点小食，为晚餐做准备，放松一下。', [
        nearB('shopping', 'POP MART Global Flagship Store', 'POP MART泡泡玛特(三里屯太古里南区店)',
          'About 2–5 minutes on foot; Beijing releases, large figures, and blind-box displays.',
          '步行约2–5分钟；北京限定、大型手办与盲盒陈列。',
          '北京市朝阳区三里屯路19号院三里屯太古里南区LG层SLG58', 'https://www.amap.com/place/B0FFH7RFH4'),
        nearB('activity', 'GENTLE MONSTER BEIJING', 'GENTLE MONSTER(北京SKP-S店)',
          'About 5–10 minutes on foot; surreal retail installations.',
          '步行约5–10分钟；超现实零售艺术装置。',
          '北京市朝阳区建国路86号SKP-S南馆3层D3009', 'https://www.amap.com/place/B0H6YS82L0'),
        nearB('shopping', 'Page One Bookstore', '中信书店(北京朝悦店)',
          'About 5–10 minutes on foot; design books, magazines.',
          '步行约5–10分钟；设计类书籍与杂志。',
          '北京市朝阳区北京城区朝阳北路101号朝阳大悦城9层中信书店(6号/4号电梯直达)', 'https://www.amap.com/place/B0MR6L15D6'),
        nearB('shopping', 'Sanlitun 3.3 Building', '三里屯3.3大厦',
          'About 5–10 minutes on foot; independent fashion stalls and compact local-label browsing.',
          '步行约5–10分钟；独立时装摊位与本土品牌小店。',
          '北京市朝阳区三里屯路33号', 'https://www.amap.com/place/B000A80TPS'),
      ]),
      itemB('18:00', 'meal', 'Siji Minfu Roast Duck (Dongsi Shitiao Branch)', '四季民福烤鸭店（东四十条店）', 'Dongcheng', '东城区',
        '北京市东城区东四街道平安大街东四十条21号', 'https://www.amap.com/place/B000A8WB65', true,
        'Online queue number for seven, or drop by to pick up a physical waitlist card; confirm details about reservations.',
        '线上取七人的排队号，或到店领取实体等位卡；确认预订相关细节。', [
        nearB('sight', 'Nanxincang Cultural and Leisure Street', '南新仓文化休闲街',
          'Located at the same address; preserved 600-year-old Ming–Qing imperial granaries converted into a street.',
          '就在同一地址；由600年历史的明清皇家粮仓改建而成的文化休闲街。',
          '北京市东城区东四十条22号(近东门仓胡同)', 'https://www.amap.com/place/B000A87GGJ'),
        nearB('sight', 'Longfusi Cultural District', '隆福寺街区',
          'Short Didi ride west; a fashionable old-Beijing renewal district mixing design shops, outdoor brands, collectibles, creative food and rooftop city views.',
          '向西打车片刻即到；时髦的老北京更新街区，汇集设计小店、户外品牌、潮玩、创意美食与天台城景。',
          '北京市东城区隆福寺街95号(东四地铁站E西北口步行210米)', 'https://www.amap.com/place/B0L2U9FKU9'),
      ]),
      itemB('20:30', 'wellness', 'Zhengyuan Blind Massage', '正元盲人按摩(东直门南大街2号院店)', 'Dongzhimenwai', '东直门',
        '北京市东城区东直门南大街甲2号(东直门地铁站C东南口步行330米)', 'https://www.amap.com/place/B0HRPY3B7T', true,
        'Approximately 104–114 CNY per person; can look at alternatives or Dianping for coupons.',
        '约每人104–114元；也可比较其他店，或在大众点评找优惠券。', [
        nearB('wellness', 'Foot Massage Liangzi (Sanlitun–Dongzhimen Branch)', '良子头等舱(三里屯东直门工体店)',
          'Request one 60–90 minute session in one big room; check for coupons on Dianping, reservations required.',
          '要求安排在同一间大房做60–90分钟；在大众点评查优惠券，需预约。',
          '北京市朝阳区北京城区东直门外大街23号', 'https://www.amap.com/place/B000A7Z4K7'),
        nearB('wellness', 'Juxin Conditioning Massage', '聚鑫调理按摩（北京站朝内南小街店）',
          '98–100 CNY per person; check for coupons on Dianping, reservations recommended.',
          '每人98–100元；在大众点评查优惠券，建议预约。',
          '北京市东城区朝内南小街22号楼首层1号', 'https://www.amap.com/place/B0LR275NET'),
      ]),
    ]),
    day('Aug 3', 'Mon', 'Badaling, Yanqing Road Trip', '八达岭·延庆自驾', [
      itemB('06:00', 'admin', 'Rental Car Drop-off at Our Hotel', '租车送至酒店', 'Chaoyang', '朝阳区',
        BJ_HOTEL_ADDR, BJ_HOTEL_MAP, true,
        'Rent on Dianping. Arrange for hotel drop-off. Confirm driving restrictions.',
        '在大众点评租车，安排送车到酒店，确认限行规定。'),
      itemB('06:15–07:30', 'transit', 'Drive to Badaling', '驾车前往八达岭长城地面停车场', 'Yanqing District', '延庆区',
        '北京市延庆区G6京藏高速58号出口', 'https://www.amap.com/place/B000A8WDPU', false,
        'Use Amap routing and the assigned parking / shuttle plan.',
        '使用高德导航，按指定的停车与接驳方案前往。'),
      itemB('08:00–11:30', 'sight', 'Badaling Great Wall', '八达岭长城', 'Badaling', '八达岭',
        '北京市延庆区G6京藏高速58号出口', 'https://www.amap.com/place/B000A45467', true,
        'Take the North cableway to N7, climb through N8, regroup beyond the N9–N10 chokepoints, descend near N11, and exit via Bear Park. Expect moderate-to-hard uneven stairs, almost no shade, and exposed weather: carry 0.75–1 L water each, wear grippy shoes, and leave for lightning, high wind, or an official closure. To add route / visit plan information here.',
        '乘北线索道至北7楼，徒步经北8楼，过北9–北10楼拥堵点后集合，在北11楼附近下城，经熊乐园出口离开。台阶高低不平、难度中上，几乎无遮阴且天气多变：每人携带0.75–1升水，穿防滑鞋；遇雷电、大风或官方关闭须撤离。路线/游览计划信息待补充。'),
      itemB('12:00–13:00', 'meal', 'Lunch: Fudoutang No. 69, Liugou', '柳沟豆腐宴69号福豆堂', 'Yanqing', '延庆区',
        '北京市延庆区胡柳路', 'https://www.amap.com/place/B0FFFADEPQ', true,
        'Request one table for seven and the Yanqing fire-basin tofu banquet; confirm Monday opening, exact entrance, meal timing, price.',
        '订一桌七人的延庆火盆锅豆腐宴；确认周一是否营业、准确入口、用餐时间和价格。'),
      itemB('13:15–14:00', 'sight', 'Yongning Ancient Town', '永宁古城', 'Yanqing', '延庆区',
        '北京市延庆区昌赤路', 'https://www.amap.com/place/B0FFH6KSNT', false,
        'Navigate to Yuhuang Pavilion, walk one market-street loop, maybe buy a fresh Yongning huoshao; leave on time for the gorge boat.',
        '导航至玉皇阁，沿市集街走一圈，可买个现做的永宁火烧；按时出发去龙庆峡乘船。', [
        nearB('sight', 'Yuhuang Pavilion', '玉皇阁',
          'About 2–5 minutes on foot; use the pavilion at Gongchen Street 100 as the navigation pin.',
          '步行约2–5分钟；以拱辰街100号的玉皇阁作为导航定位点。',
          '北京市延庆区拱辰街100号', 'https://www.amap.com/place/B000A9LFRK'),
        nearB('restaurant', 'Yongning Tofu (Gongchen St)', '永宁豆腐(拱辰街店)',
          'About 5–10 minutes on foot; Yongning’s sour-pulp tofu tradition.',
          '步行约5–10分钟；永宁传统酸浆豆腐。',
          '北京市延庆区永宁镇拱辰街60号', 'https://www.amap.com/place/B0FFLJ5OUB'),
      ]),
      itemB('14:30', 'sight', 'Longqing Gorge', '龙庆峡风景区', 'Jiuxian', '延庆区',
        '北京市延庆区旧县镇古城村北', 'https://www.amap.com/place/B000A02891', true,
        'Head straight for the main gorge boat ride — closes at 4pm and the last ride is 4:30pm. Can be more relaxed after that; maybe the Shenxianyuan cableway if the weather is good.',
        '直奔主峡谷游船——下午4点停止入场，末班船4点半。之后可以放松些；天气好的话可考虑神仙院索道。', [
        nearXiadu,
        nearB('sight', 'Sanlihe Wetland Park', '三里河湿地公园',
          'About 20–30 minutes by car; choose a brief boardwalk section.',
          '驾车约20–30分钟；选一小段木栈道走走即可。',
          '北京市延庆区庆园街与玉皇阁大街交叉口西', 'https://www.amap.com/place/B000A9JSXN'),
      ]),
      itemB('17:00–18:00', 'meal', 'Ta Hou Meat Pie', '太后肉饼', 'Longqing Gorge–Jiuxian', '延庆·龙庆峡—旧县',
        '北京市延庆区旧县镇古城村昊龙宾馆北50米', 'https://www.amap.com/place/B0J6458YA9', true,
        'Order the signature layered meat pie.',
        '点招牌千层肉饼。', [
        nearXiadu,
      ]),
      itemB('18:30–19:00', 'activity', 'Guishui Park', '妫水公园', 'Yanqing Town–Gui River', '延庆·延庆城区—妫河',
        '北京市延庆区延庆镇东外小区', 'https://www.amap.com/place/B0J3M7GF4C', false,
        'Golden-hour walk, group photographs, drinks, toilets; the August 3 sunset reference is about 19:26. Delay getting into Beijing during rush hour.',
        '黄金时段散步、合影、买水、上洗手间；8月3日日落参考时间约19:26。避开晚高峰再返回北京。'),
      itemB('19:00–22:00', 'transit', 'Return to Hotel', '返回酒店', 'Beijing', '北京',
        '北京市西城区', 'https://www.amap.com/place/B000A8VITQ', false,
        'Flex time; open to any spots along the way or a drive around town.',
        '弹性时间；可顺路停靠任意地点，或在城里兜兜风。'),
    ]),
    day('Aug 4', 'Tue', 'Central Axis, Palace, Jingshan, Acrobat Show', '中轴线·故宫·景山·杂技', [
      itemB('07:00–07:10', 'admin', 'Rental Car Return from Hotel', '酒店门口还车', 'Chaoyang', '朝阳区',
        BJ_HOTEL_ADDR, BJ_HOTEL_MAP, true,
        'Arrange with the rental car company for pickup.',
        '与租车公司约好上门取车。'),
      itemB('07:10–07:30', 'transit', 'Didi to Tian’anmen Security Entrance', '打车前往天安门安检口', 'Dongcheng', '东城区',
        '北京市东城区东长安街', 'https://www.amap.com/place/B000A83C1S', false,
        'Use two cars to the permitted drop-off area, then walk to the checkpoint on the reservation.',
        '分乘两辆车到允许落客的区域，再步行前往预约对应的安检口。'),
      itemB('07:30–08:00', 'sight', 'Tian’anmen Square', '天安门广场', 'Dongcheng', '东城区',
        '北京市东城区东长安街', 'https://www.amap.com/place/B000A83C1S', true,
        'Clear security checkpoints; consider bringing items in a clear plastic bag to speed up security. Notable: Monument to the People’s Heroes, the Tian’anmen façade and Palace.',
        '通过安检；可将随身物品装入透明塑料袋加快过检。看点：人民英雄纪念碑、天安门城楼。'),
      itemB('08:30–12:00', 'sight', 'Forbidden City — Palace Museum', '紫禁城·故宫博物院', 'Dongcheng', '东城区-故宫—东华门',
        '北京市东城区景山前街4号', 'https://www.amap.com/place/B000A8UIN8', true,
        'Enter only at Meridian Gate. Follow through the Three Great Halls, Gate of Heavenly Purity, and the Imperial Garden. Exit only at Shenwu Gate. Route information to be added.',
        '仅从午门进入。依次游览三大殿、乾清门与御花园。仅从神武门出。路线信息待补充。'),
      itemB('12:00–13:00', 'activity', 'Jingshan Park Hike', '景山公园', 'Xicheng', '西城区',
        '北京市西城区景山西街44号', 'https://www.amap.com/place/B000A7I1OL', true,
        'Enter at the South Gate, cross the Qiwang Tower forecourt, climb to Wanchun Pavilion for the palace panorama view, then leave on the east side through the East Gate for lunch.',
        '从南门进入，经绮望楼前庭，登万春亭俯瞰故宫全景，然后从东门出去吃午餐。'),
      itemB('13:00–15:00', 'meal', 'Lunch & Casual Walk: Yu’er–Mao’er–Ju’er Hutongs', '雨儿·帽儿·菊儿胡同', 'Dongcheng', '东城区',
        '雨儿胡同', 'https://www.amap.com/place/B0FFGQ4RSW', false,
        'Fangzhuanchang No. 69 Zhajiangmian (Fangzhuanchang Hutong branch) is an option — grab a physical queue ticket and walk around while waiting.',
        '可在方砖厂69号炸酱面（方砖厂胡同店）用餐——需现场取号，等位时四处逛逛。', [
        nearB('shopping', 'Nanluoguxiang', '南锣鼓巷',
          'About 2–5 minutes on foot; easy tea, dessert, and design-retail browsing.',
          '步行约2–5分钟；喝茶、吃甜品、逛设计小店都很方便。',
          '北京市东城区交道口街道南大街(南锣鼓巷地铁站E西北口旁)', 'https://www.amap.com/place/B0FFFAH7I9'),
        nearB('shopping', 'Gulou East Street', '鼓楼东大街',
          'About 5–10 minutes by car or 10–15 minutes on foot; local shops, cafés, desserts, and street life.',
          '驾车约5–10分钟或步行10–15分钟；本地小店、咖啡馆、甜品与街头生活。',
          '北京市西城区', 'https://www.amap.com/place/B0J3M9IB7X'),
      ]),
      itemB('15:00–16:30', 'rest', 'Return to Hotel & Recharge', '返回住处休整', 'Chaoyang', '朝阳区',
        BJ_HOTEL_ADDR, BJ_HOTEL_MAP, false,
        'Cool down, shower, change, and get ready for tonight’s show.',
        '降降温、冲个澡、换身衣服，准备看今晚的演出。'),
      itemB('17:30–19:00', 'show', 'Flying Acrobatic Show', '飞翔杂技(北京朝阳剧场)', 'Chaoyang', '朝阳区',
        '北京市朝阳区呼家楼街道东三环北路36号', 'https://www.amap.com/place/B0G2C57HTG', true,
        'Acrobatics; showtimes at 16:00, 17:30, and 19:00.',
        '杂技表演；场次为16:00、17:30和19:00。', [
        nearB('restaurant', 'Hu Da Restaurant (Guijie Main Branch)', '胡大饭馆24h(簋街总店)',
          'Queue remotely or on site; allow for peak waits that can exceed three hours.',
          '可线上或到店排队；高峰等位可能超过三小时。',
          '北京市东城区东直门内大街233号', 'https://www.amap.com/place/B0FFF9XSVV'),
        nearTheBox,
      ]),
    ]),
    day('Aug 5', 'Wed', 'Temple of Heaven, Tufting, Departure', '天坛·簇绒·启程', [
      itemB('06:30–10:00', 'sight', 'Temple of Heaven', '天坛公园', 'Dongcheng', '东城区',
        '北京市东城区天坛东里甲1号', 'https://www.amap.com/place/B000A81CB2', true,
        'Enter at the East Gate, follow the one-way monument sequence through the Hall of Prayer, Danbi Bridge, Imperial Vault and Echo Wall, and Circular Mound, then leave at the South Gate.',
        '从东门进入，按单向顺序游览祈年殿、丹陛桥、皇穹宇与回音壁、圜丘，最后从南门离开。', [
        nearB('restaurant', 'Tiantan Coffee Shop Fuyin (East Second Gate)', '天坛福饮咖啡店',
          'Route-side drink option.',
          '顺路的饮品选择。',
          '北京市东城区天坛公园东门(天坛东门地铁站A2西北口步行340米)', 'https://www.amap.com/place/B0HU1DCGOE'),
        nearB('shopping', 'Temple of Heaven Cultural & Creative Store', '天坛文创店（丹陛桥西侧）',
          'Small souvenir stop.',
          '小型文创纪念品店。',
          '北京市东城区天坛东里甲1号天坛公园', 'https://www.amap.com/place/B0LAARJJQ8'),
      ]),
      itemB('10:30–11:00', 'admin', 'Check Out of Apartment', '民宿退房', 'Chaoyang', '朝阳区',
        BJ_HOTEL_ADDR, BJ_HOTEL_MAP, true,
        'Check out of the apartment; figure out bag storage with the host.',
        '办理退房，并与房东确认行李寄存。'),
      itemB('11:00–12:30', 'rest', 'Flex Time for Lunch or Departure Prep', '弹性时间·午餐或行前准备', 'Chaoyang Joy City–Qingnian Road', '朝阳·朝阳大悦城—青年路',
        '北京市朝阳区朝阳北路101号朝阳大悦城B1层', 'https://www.amap.com/place/B0LUU5PXF7', false,
        'Lunch TBD; just take it chill before we go tufting — free time.',
        '午餐待定；簇绒前放松一下——自由活动。'),
      itemB('12:30–16:00', 'craft', 'Tufting at TuTu Cat DIY', 'TuTu猫DIY·手工毛线（珠江罗马嘉园西区店）', 'Chaoyang', '朝阳区',
        '北京市朝阳区北京城区朝阳北路青年汇104楼610室', 'https://www.amap.com/place/B0K3SMNLRU', true,
        'Call ahead to schedule a session; they also have another branch we could go to.',
        '提前致电预约场次；他们还有另一家分店可选。'),
      itemB('21:00', 'transit', 'Steven’s Departure to SYD — Beijing Capital International Airport', '北京首都国际机场·飞往悉尼', 'Shunyi', '顺义区',
        BJ_AIRPORT_ADDR, BJ_AIRPORT_MAP, false,
        'Depart Beijing.',
        '离开北京。'),
    ]),
  ],
};

const TRIP = {
  title: { en: 'Family China Trip', zh: '家庭中国之旅' },
  dates: { en: 'Jul 26 – Aug 6, 2026', zh: '2026 年 7 月 26 日 – 8 月 6 日' },
  cities: [guangzhou, shanghai, beijing],
};

const I18N = {
  tripTitle: { en: 'Family China Trip', zh: '家庭中国之旅' },
  subtitle: { en: '3 cities · 12 days', zh: '3 座城市 · 12 天' },
  schedule: { en: 'Schedule', zh: '行程' },
  hotel: { en: 'Hotel', zh: '住宿' },
  address: { en: 'Address', zh: '地址' },
  openMaps: { en: 'Open in Maps', zh: '在地图中打开' },
  booking: { en: 'Booking', zh: '需预订' },
  bookingRequired: { en: 'Booking required', zh: '需提前预订' },
  noBooking: { en: 'Walk-in · no booking', zh: '无需预订' },
  nearby: { en: 'Nearby', zh: '附近' },
  nearbyHint: { en: 'Sights, food & things to do around here', zh: '周边的景点、美食与活动' },
  mustEatTitle: { en: 'Taste of', zh: '风味' },
  mustEat: { en: 'Must-eat', zh: '必吃' },
  overview: { en: 'Overview', zh: '概览' },
  about: { en: 'About this stop', zh: '关于此行程' },
  type_activity: { en: 'Activity', zh: '活动' },
  type_meal: { en: 'Food', zh: '美食' },
  type_sight: { en: 'Sight', zh: '景点' },
  type_transit: { en: 'Transit', zh: '交通' },
  type_admin: { en: 'Admin', zh: '事务' },
  type_shopping: { en: 'Shopping', zh: '购物' },
  type_wellness: { en: 'Wellness', zh: '养生' },
  type_show: { en: 'Show', zh: '演出' },
  type_craft: { en: 'Craft', zh: '手作' },
  type_rest: { en: 'Rest', zh: '休整' },
  cat_sight: { en: 'Sight', zh: '景点' },
  cat_restaurant: { en: 'Food', zh: '美食' },
  cat_activity: { en: 'Activity', zh: '活动' },
  cat_shopping: { en: 'Shopping', zh: '购物' },
  cat_wellness: { en: 'Wellness', zh: '养生' },
  nearbyHotel: { en: 'Around the hotel', zh: '酒店周边' },
  close: { en: 'Close', zh: '关闭' },
  today: { en: 'Days', zh: '每日行程' },
  checkIn: { en: 'Check-in', zh: '入住' },
  checkOut: { en: 'Check-out', zh: '退房' },
  phone: { en: 'Phone', zh: '电话' },
  wifi: { en: 'Wi-Fi', zh: '无线网络' },
  confirmation: { en: 'Confirmation', zh: '确认号' },
  stay: { en: 'Your stay', zh: '入住信息' },
  goodToKnow: { en: 'Good to know', zh: '温馨提示' },
  hotelDetails: { en: 'Hotel details', zh: '酒店详情' },
  directions: { en: 'Directions', zh: '导航' },
};

module.exports = { TRIP, I18N };
