// Approved day-hero selections for the public itinerary.
// Source metadata stays in code; the UI renders only the selected local assets.
const DAY_IMAGES = {
  'gz-d1': {
    candidateId: 'gz-d1-d',
    src: 'images/gz-1.webp',
    alt: 'Sacred Heart Cathedral framed by Yide Road in Guangzhou',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sacred_Heart_Cathedral_of_Guangzhou_2025.06_05.jpg',
    owner: 'Shujianyang',
    rightsStatus: 'CC BY-SA 4.0',
  },
  'gz-d2': {
    candidateId: 'gz-d2-d',
    src: 'images/gz-2.webp',
    alt: 'Lantern-lined walkway at Chen Clan Ancestral Hall in Guangzhou',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lanterns_cover_the_walkway.jpg',
    owner: 'VioletShi',
    rightsStatus: 'CC BY-SA 4.0',
  },
  'gz-d3': {
    candidateId: 'gz-d3-e',
    src: 'images/gz-3.webp',
    alt: 'Wulong Pavilion and Qixing Bridge at Seven Star Crags',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wulong_Pavilion_%26_Qixing_Bridge,_Seven_Star_Crags_20260217.jpg',
    owner: 'Jasonjiang.1998',
    rightsStatus: 'CC BY-SA 4.0',
  },
  'gz-d4': {
    candidateId: 'gz-d4-e',
    src: 'images/gz-4.webp',
    alt: 'Five Rams sculpture in Yuexiu Park during the day',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Five-Ram_Sculpture_of_Guangzhou.jpg',
    owner: 'xiquinhosilva',
    rightsStatus: 'CC BY 2.0',
  },
  'sh-d1': {
    candidateId: 'sh-d1-a',
    src: 'images/sh-1.webp',
    alt: 'Jing’an Temple framed by Shanghai neighborhood towers at night',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Side_view_and_pagoda_of_Jing%27an_Temple,_Shanghai,_at_night.jpg',
    owner: 'David Leo Veksler',
    rightsStatus: 'CC BY-SA 2.0',
  },
  'sh-d2': {
    candidateId: 'sh-d2-b',
    src: 'images/sh-2.webp',
    alt: 'Wukang Building at a busy French Concession street corner in Shanghai',
    sourceUrl: 'https://unsplash.com/photos/U_56L_fyZa0',
    owner: 'krzhck',
    rightsStatus: 'Unsplash License',
  },
  'sh-d3': {
    candidateId: 'sh-d3-a',
    src: 'images/sh-3.webp',
    alt: 'Layered pavilions and traditional roofscape at Yu Garden in Shanghai',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Shanghai_-_Yu_Garden_-_0031.jpg',
    owner: 'Stefan Fussan',
    rightsStatus: 'CC BY-SA 3.0',
  },
  'sh-d4': {
    candidateId: 'sh-d4-e',
    src: 'images/sh-4.webp',
    alt: 'Bao Da Xiang local fashion shopping on East Nanjing Road',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bao_Da_Xiang-20220828.jpg',
    owner: 'Shwangtianyuan',
    rightsStatus: 'CC BY-SA 4.0',
  },
  'sh-d5': {
    candidateId: 'sh-d5-c',
    src: 'images/sh-5.webp',
    alt: 'Waibaidu Bridge, the Oriental Pearl Tower, and Shanghai night lights',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Night_lights_of_Shanghai.jpg',
    owner: 'David Zhang',
    rightsStatus: 'CC BY-SA 2.0',
  },
  'bj-d1': {
    candidateId: 'bj-d1-d',
    src: 'images/bj-1.webp',
    alt: 'Taikoo Li Sanlitun plaza in Beijing at dusk',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sanlitun_at_dusk.jpg',
    owner: 'Leeluv',
    rightsStatus: 'CC BY-SA 3.0',
  },
  'bj-d2': {
    candidateId: 'bj-d2-a',
    src: 'images/bj-2.webp',
    alt: 'The Great Wall crossing green mountain ridges outside Beijing',
    sourceUrl: 'https://unsplash.com/photos/zhiQORykuwQ',
    owner: 'Jamie Street',
    rightsStatus: 'Unsplash License',
  },
  'bj-d3': {
    candidateId: 'bj-d3-e',
    src: 'images/bj-3.webp',
    alt: 'Guardian lion beside an imperial hall at the Forbidden City in Beijing',
    sourceUrl: 'https://unsplash.com/photos/LkyYLdL3WxE',
    owner: 'Rafik Wahba',
    rightsStatus: 'Unsplash License',
  },
  'bj-d4': {
    candidateId: 'bj-d4-a',
    src: 'images/bj-4.webp',
    alt: 'Hall of Prayer for Good Harvests at the Temple of Heaven in Beijing',
    sourceUrl: 'https://unsplash.com/photos/AFXV5ciWPkM',
    owner: 'krzhck',
    rightsStatus: 'Unsplash License',
  },
};

module.exports = { DAY_IMAGES };
